config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

core/urls.py
from django.urls import path

from rooms import views as room_views

app_name = "core"


urlpatterns = [
    path("", room_views.HomeListView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path

from rooms import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/partials/footer.html
<section class="py-20 min-h-fit bg-slate-200">
    &copy;2023
</section>

templates/partials/nav.html
{% load i18n %} 
{% load static %}

<nav class="flex items-center justify-between px-5 py-3 shadow">
  <h2 class="flex items-center gap-1">
    <img class="w-10" src="{% static 'img/logo.png' %} " alt="airbnb logo" />
    <a href="{% url 'core:home' %}" class="text-4xl">DjangoBnB</a>
  </h2>
  <ul class="flex gap-4 text-sm font-medium">
    <li>
        <a href="#">About</a>
    </li>
    <li>
        <a href="#">Contact</a>
    </li>
    <li>
        <a href="{% url 'rooms:search' %}">Search</a>
    </li>
  </ul>
  <ul class="flex gap-4">
    {% if request.user.is_authenticated %}
        <li>
            <a href="{% url 'account_logout' %}">Logout</a>
        </li>
    {{user.get_full_name}} {% else %}
        <li>
            <a href="{% url 'account_login' %}">Log In</a>
        </li>
        <li>
            <a href="{% url 'account_signup' %}">Sign Up</a>
        </li>
    {% endif %}
  </ul>
</nav>

templates/partials/pagination.html
<section class="flex items-center justify-between">
    <div>
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}
    </div>
    <p class="text-l">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}
    </p>
    <div>
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages}}">Last &raquo;</a>
        {% endif %}
    </div>
</section>